name: Nightly Android

on:
  push:
    branches: [ tester ]
  pull_request:
    branches: [ tester ]

env:
  # runner.workspace = /home/runner/work/serenity
  # github.workspace = /home/runner/work/serenity/serenity
  LADYBIRD_SOURCE_DIR: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  VCPKG_ROOT:  ${{ github.workspace }}/Toolchain/Tarballs/vcpkg
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os_name: ['Android']
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Environment
        uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os_name }}
          arch: 'Lagom'

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3

      # === PREPARE FOR BUILDING ===

      - name: Restore Caches
        uses: ./.github/actions/cache-restore
        id: 'cache-restore'
        with:
          os: ${{ matrix.os_name }}
          arch: 'Lagom'
          cache_key_extra: 'Nightly Android'
          serenity_ccache_path: ${{ env.CCACHE_DIR }}
          download_cache_path: ${{ github.workspace }}/Build/caches

      - name: Assign Build Parameters
        id: 'build-parameters'
        run: |
          echo "host_cc=$(xcrun --find clang)" >> "$GITHUB_OUTPUT"
          echo "host_cxx=$(xcrun --find clang++)" >> "$GITHUB_OUTPUT"

      - name: Install NDK
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;32.0.0" "platforms;android-34"
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;26.1.10909125"

      - name: Build
        working-directory: ${{ github.workspace }}/Ladybird/Android
        run: ./gradlew assembleRelease
        env:
          GRADLE_OPTS: '-Xmx3072m'
          SERENITY_CACHE_DIR: ${{ github.workspace }}/Build/caches

      - name: Save Caches
        uses: ./.github/actions/cache-save
        with:
          arch: 'Lagom'
          serenity_ccache_path: ${{ env.CCACHE_DIR }}
          serenity_ccache_primary_key: ${{ steps.cache-restore.outputs.serenity_ccache_primary_key }}
